server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: promtail_positions.yaml

clients:
  - url: http://10.0.2.15:3100/loki/api/v1/push

scrape_configs:
  - job_name: opendr-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: opendr
          host: windows-endpoint
          __path__: C:\ProgramData\edrsvc\log\output_events\*.txt
